apiName: Event
label: 行動
pluralLabel: 行動
description: カレンダー行動・会議の管理
fields:
  - apiName: Subject
    label: 件名
    type: Text
    length: 255
  - apiName: Description
    label: 説明
    type: LongTextArea
    length: 32768
    visibleLines: 5
  - apiName: StartDateTime
    label: 開始日時
    type: DateTime
    required: true
  - apiName: EndDateTime
    label: 終了日時
    type: DateTime
    required: true
  - apiName: Location
    label: 場所
    type: Text
    length: 255
  - apiName: IsAllDayEvent
    label: 終日イベント
    type: Checkbox
    defaultValue: false
  - apiName: WhoId
    label: 名前
    type: Lookup
    referenceTo: Contact
    relationshipName: Events
    relationshipLabel: 行動
  - apiName: WhatId
    label: 関連先
    type: Lookup
    referenceTo: Account
    relationshipName: Events
    relationshipLabel: 行動
  - apiName: OwnerId
    label: 任命先
    type: Lookup
    referenceTo: User
    relationshipName: OwnedEvents
