apiName: OrderItem
label: 注文品目
pluralLabel: 注文品目
description: 注文の品目明細
fields:
  - apiName: OrderId
    label: 注文
    type: Lookup
    referenceTo: Order
    relationshipName: OrderItems
    relationshipLabel: 注文品目
    required: true
  - apiName: Product2Id
    label: 商品
    type: Lookup
    referenceTo: Product2
    relationshipName: OrderItems
    relationshipLabel: 注文品目
  - apiName: PricebookEntryId
    label: 価格表エントリ
    type: Lookup
    referenceTo: PricebookEntry
    relationshipName: OrderItems
  - apiName: Quantity
    label: 数量
    type: Number
    precision: 18
    scale: 2
    required: true
  - apiName: UnitPrice
    label: 単価
    type: Currency
    precision: 18
    scale: 0
    required: true
  - apiName: TotalPrice
    label: 合計価格
    type: Currency
    precision: 18
    scale: 0
  - apiName: Description
    label: 説明
    type: Text
    length: 255
